// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdgkencuqwhrtciogvfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZ2tlbmN1cXdocnRjaW9ndmZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODYyODgsImV4cCI6MjA2OTk2MjI4OH0.q2JiIMBIhujfFz8neR7eDnLq7IntEgb0t-r9FBgtLts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});